export const INITIAL_STATE = {
  postCheckoutIsLoading: false,
  postCheckoutErrorMessage: null,
  postCheckoutSuccessMessage: null,
  postCheckoutWithoutCartIsLoading: false,
  postCheckoutWithoutCartErrorMessage: null,
  postCheckoutWithoutCartSuccessMessage: null,
  paymentMethodsIsLoading: false,
  paymentMethodsErrorMessage: null,
  paymentMethodsSuccessMessage: null,
  paymentMethods: [],
  selectedPayment: null,
  cartItems: [],
  checkVoucherSuccessMessage: null,
  checkVoucherErrorMessage: null,
  checkVoucherIsLoading: false,
  paymentDetailItems: [],
  paymentDetailItemsTemp: [],
  total: 0,
}
