export const INITIAL_STATE = {
  airports: [],
  airportsIsLoading: false,
  airportsErrorMessage: null,
  airportCoverages: [],
  airportCoveragesIsLoading: false,
  airportCoveragesErrorMessage: null,
  airportPlaceDetail: null,
  airportPlaceDetailIsLoading: false,
  airportPlaceDetailErrorMessage: null,
  airportPlaceCoordinate: [],
  airportPlaceCoordinateIsLoading: false,
  airportPlaceCoordinateErrorMessage: null,
  distanceBetweenOriginAndDestination: null,
  distanceBetweenOriginAndDestinationIsLoading: false,
  distanceBetweenOriginAndDestinationErrorMessage: null,
  zone: null,
  zoneIsLoading: false,
  zoneErrorMessage: null,
  selectedDate: new Date(),
}
